[project]
name = "gd-providers-api"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115",
    "uvicorn>=0.30",
    "pydantic>=1.10,<3",
]

[project.optional-dependencies]
test = ["pytest"]
