[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aneel_tariffs"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "pynats",
    "asyncapi-nats-client",
]
