version: "3.9"
services:
  api:
    build: .
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [postgres, nats]
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ysh
      POSTGRES_USER: ysh
      POSTGRES_PASSWORD: secret
    ports: ["5432:5432"]
  nats:
    image: nats:2.10
    command: ["-js","-sd","/data"]
    ports: ["4222:4222","8222:8222"]
