[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "origination_api"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "asyncpg",
    "pydantic",
    "nats-py",
]
